name: Deployment workflow

on: 
  push:
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  terraform_deployment:
    name: Terraform Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Install Terraform
        run: |
          # Ensure that the system is up to date and gnupg in installed
          sudo apt-get update 
          sudo apt-get install -y gnupg software-properties-common curl

          # Install HashiCorp's GPG key
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg

          # Add the official HashiCorp repository
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
          https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
          sudo tee /etc/apt/sources.list.d/hashicorp.list

          # Update apt and install Terraform
          sudo apt-get update
          sudo apt-get install terraform

          # Verify installation
          terraform -version

      - name: Checkout the terraform code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0            # full history
          ref: ${{ github.ref }}    # ensure correct branch/PR ref
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Initializing
        run: |
          terraform init

      - name: Plan the terraform infrastructure to destroy
        run: |
          terraform plan -destroy -out=infra-destroy.tfplan

      - name: Apply the terraform infrastructure to destroy
        run: |
          terraform apply -auto-approve "infra-destroy.tfplan"